# Generated by Django 3.2.4 on 2021-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_fourth', '0005_auto_20210722_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
